### ISSUE TITLE
tidy_infernal_gff.py problem

### ISSUE THREAD

**Issue by JWDebler** [darcyabjones/pante#7]
Hi Darcy,
I keep running into an error probably with infernal.
Attached is the error message and the 2 input files.
There is only a single entry in the `infernal.gff3` file, not sure if that is where the problem stems from.

Cheers,
Johannes

```
Error executing process > 'tidyInfernalMatches (P9424.ragtag)'

Caused by:
  Process `tidyInfernalMatches (P9424.ragtag)` terminated with an error exit status (1)

Command executed:

  awk -F '\t' '
    BEGIN {OFS="\t"}
    {$9=gensub(":", "=", "g", $9); print}
    ' infernal.gff3     | tidy_infernal_gff.py       --go rfam2go       --best       --source "Rfam"       --type nucleotide_match       -o tidied.gff3       -

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Traceback (most recent call last):
    File "/home/ubuntu/pante/bin/tidy_infernal_gff.py", line 137, in <module>
      main()
    File "/home/ubuntu/pante/bin/tidy_infernal_gff.py", line 79, in main
      go = parse_rfam2go(args.go)
    File "/home/ubuntu/pante/bin/tidy_infernal_gff.py", line 64, in parse_rfam2go
      rfam, go = line.strip().split(">", maxsplit=1)
  ValueError: not enough values to unpack (expected 2, got 1)

Work dir:
  /data/2021-07-01_kewell_p9424/assembly/circos/Al4_Kewell/work/f0/5ff966c8c334f807a15a35419358e9

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

[infernal.gff3.txt](https://github.com/darcyabjones/pante/files/6985809/infernal.gff3.txt)

[rfam2go.txt](https://github.com/darcyabjones/pante/files/6985806/rfam2go.txt)

**Comment by JWDebler** [comment]
disabling infernal `--noinfernal` lets the pipeline finish.

**Comment by JWDebler** [comment]
I dug a little deeper, and the problem started to occur with Rfam 14.6. I had a look at the 3 files panTE uses, and the only difference I could find is that `rfam2go` as of version 14.6 now has a bunch of header lines. Could this be tripping up the method in `tidy_infernal_gff.py`?

The new rfam2go file looks like this:

```
!version date: 2021/07/02
!description: A mapping of GO terms to Rfam release 14.6.
!external resource: https://rfam.org/
!citation: Kalvari et al. (2020) Nucl. Acids Res. 49: D192-D200
!contact: rfam-help@ebi.ac.uk
!
Rfam:RF00001 5S_rRNA > GO:structural constituent of ribosome ; GO:0003735
Rfam:RF00001 5S_rRNA > GO:ribosome ; GO:0005840
Rfam:RF00002 5_8S_rRNA > GO:structural constituent of ribosome ; GO:0003735 
```

May have to add something to ignore all those lines starting with "!" (not sure if the below is correct python :-) )
```
def parse_rfam2go(handle):
    out = defaultdict(list)
    for line in handle:
        if line.startswith("!"): // inserted 
              continue          //  by
        else:                  //   JD

             rfam, go = line.strip().split(">", maxsplit=1)
             rfam_acc, rfam_name = rfam.strip().split()
             go_acc, go_name = go.strip().split(";", maxsplit=1)

             rfam_acc_stripped = rfam_acc.strip().split(":", maxsplit=1)[-1].strip()
             out[rfam_acc_stripped].extend([go_acc.strip(), go_name.strip()])

         return out
```

**Comment by darcyabjones** [comment]
Yep that'll do it.

Commit in #79820e0

Your python code was fine.
It's usually a good idea to strip whitespace the parser shouldn't be whitespace sensitive. (in case for whatever reason theres a space before the !).
Also since the loop will immediately skip to the next element when you call `continue` there's no need for the `else`.
Nothing wrong with having it, different programming languages have different preferences, this tends to be what people prefer in python.

**Comment by JWDebler** [comment]
Can confirm, it is working. 👍
